const actions={

    FETCH_ALL:"FETCH_ALL",
    FETCH_UNAPPROVED:"FETCH_UNAPPROVED",
    FETCH_PROPERTYDEALERS:"FETCH_PROPERTYDEALERS",
    UPDATE_ALL:"UPDATE_ALL",
    ADD_USER:"ADD_USER",
    UPDATE_LIMIT:"UPDATE_LIMIT"


};
export default actions;