const actions={

     FETCH_ALL:"FETCH_ALL",
     FETCH_PENDING : "FETCH_PENDING",
     FETCH_APPROVED : "FETCH_APPROVED",
     FETCH_REJECTED : "FETCH_REJECTED",
     APPROVE_LISTING : "APPROVE_LISTING",
     REJECT_LISTING : "REJECT_LISTING",
     APPROVE_FEATURES: "APPROVE_FEATURES",
     FETCH_APPROVED_REQUESTED: "FETCH_APPROVED_REQUESTED"
};
export default actions;
